### ISSUE TITLE
project name confliction

### ISSUE THREAD

**Issue by longlene** [lokedhs/cl-markup#1]
Hi, there is already a project which name is: cl-markup https://github.com/arielnetworks/cl-markup and there are some projects depend on it. It is also collected by the quicklisp.
It may be better to rename this repo to cl-commonmark or cl-cmark?

**Comment by lokedhs** [comment]
I'm not against the idea of changing the name, although cl-commonmark is a bad name since the markup format used in the project has diverged significantly from that of commonmark, and there is no plan to change that.

Also, this project is not on Quicklisp, and there is as far as I know only one project that uses it. Therefore, I don't see the need to go through the hassle of changing the name at the moment.

If there are other users of this project, then it would be a different matter.
